# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='鏍囬\ue57d')),
                ('content', models.TextField(verbose_name='鍐呭\ue190')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='鍙戝竷鏃堕棿')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='鏇存柊鏃堕棿')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='濮撳悕')),
                ('sex', models.CharField(max_length=5, verbose_name='鎬у埆')),
                ('info', models.TextField(verbose_name='绠�浠�')),
                ('birth_time', models.DateTimeField(verbose_name='鍑虹敓骞存湀')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='鏇存柊鏃堕棿')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='濮撳悕')),
                ('user_task', models.CharField(default='尚未更新...', max_length=256, null=True, verbose_name='任务')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='濮撳悕')),
                ('user_longi', models.CharField(max_length=25, null=True, verbose_name='经度')),
                ('user_lati', models.CharField(max_length=25, null=True, verbose_name='纬度')),
                ('user_forbid', models.NullBooleanField(default='0', verbose_name='是否黑名单')),
                ('user_photo', models.CharField(default='project-2.jpg', max_length=256, null=True, verbose_name='头像')),
                ('user_descripe', models.CharField(default='尚未更新...', max_length=256, null=True, verbose_name='描述')),
                ('user_password', models.CharField(max_length=16, verbose_name='瀵嗙爜')),
                ('user_email', models.EmailField(max_length=30, verbose_name='閭')),
                ('user_sex', models.TextField(default='尚未更新...', max_length=5, null=True, verbose_name='鎬у埆')),
                ('user_addr', models.CharField(default='尚未更新...', max_length=256, null=True, verbose_name='绠�浠�')),
                ('user_birth', models.DateTimeField(auto_now_add=True, null=True, verbose_name='鍑虹敓骞存湀')),
                ('user_sign', models.CharField(default='尚未更新...', max_length=256, null=True, verbose_name='签名')),
                ('user_intro', models.CharField(default='尚未更新...', max_length=512, null=True, verbose_name='介绍')),
            ],
        ),
    ]
