# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='姓名')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('info', models.TextField(verbose_name='简介')),
                ('birth_time', models.DateTimeField(verbose_name='出生年月')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
    ]
