# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160922_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_lati',
            field=models.CharField(max_length=25, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_longi',
            field=models.CharField(max_length=25, null=True, verbose_name='经度'),
        ),
    ]
