# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160922_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_descripe',
            field=models.CharField(max_length=256, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_forbid',
            field=models.NullBooleanField(verbose_name='是否黑名单'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.CharField(max_length=256, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=256, verbose_name='閭\ue1be\ue188'),
        ),
    ]
