# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160923_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.TextField(null=True, verbose_name='绠�浠�'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=256, verbose_name='閭'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.CharField(max_length=15, null=True, verbose_name='鎬у埆'),
        ),
    ]
