# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160923_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.CharField(max_length=256, null=True, verbose_name='绠�浠�'),
        ),
    ]
