# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160923_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=25, verbose_name='閭'),
        ),
    ]
