# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160923_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_sex',
            field=models.TextField(max_length=5, null=True, verbose_name='鎬у埆'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=30, verbose_name='閭'),
        ),
    ]
