# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160923_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_sex',
        ),
    ]
