# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateTimeField(null=True, verbose_name='鍑虹敓骞存湀'),
        ),
    ]
