# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160923_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birth',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='鍑虹敓骞存湀'),
        ),
    ]
